### ISSUE TITLE
请求支持per app hacking模块

### ISSUE THREAD

**Issue by 1536455187** [tiann/Tai-Chi#228]
## 模块名字
per app hacking
## 模块用途
Per App Hacking是一款应用优化工具的 Xposed模块，这个模块的作用:
1防止应用启动服务
2通过提醒来禁止或者延迟应用的自启动
3禁用唤醒锁防止程亨唤醒设备
4允许对单个应用设置代理
5允许对单个应用伪造时间格式: YYYY-MM-DDHH:MI
6限制位图
## 模块版本号
1.5
## 模块安装包
https://www.lanzous.com/i33qbeh

**Comment by tiann** [comment]
这个模块应该是有 BUG的，唤醒锁功能部分会不正常。以下是错误日志：

>2019-02-11 16:39:57.089 24512-24512/? E/Xposed: java.lang.NoSuchMethodError: android.os.PowerManager$WakeLock#acquire(java.lang.Long)#exact
        at de.robv.android.xposed.XposedHelpers.findMethodExact(SourceFile:344)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(SourceFile:185)
        at org.t2k269.perapphacking.HackService.handleLoadPackage(HackService.java:252)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(SourceFile:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(SourceFile:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(SourceFile:106)
        at me.weishu.exposed.ExposedBridge.doLoadModule(SourceFile:814)
        at me.weishu.exposed.ExposedBridge.loadModule(SourceFile:752)
        at me.weishu.exposed.ExposedBridge.initNative(Native Method)
        at me.weishu.exposed.ExposedBridge.init(SourceFile:176)
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.taichi.MagiskInit.b(Unknown Source:291)
        at me.weishu.taichi.MagiskInit.a(Unknown Source:0)
        at me.weishu.taichi.MagiskInit$1$1.handleMessage(Unknown Source:14)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

对应的源码：

```java
        public void acquire(long timeout) {
            synchronized (mToken) {
                acquireLocked();
                mHandler.postDelayed(mReleaser, timeout);
            }
        }
```

**Comment by tiann** [comment]
除了唤醒锁之外，其他应该已经支持：https://github.com/tiann/Tai-Chi/releases/tag/4.2.6
