### ISSUE TITLE
相机直接闪退，且第三方相机也无法使用

### ISSUE THREAD

**Issue by hxsstime** [tiann/Tai-Chi#7]
手机型号：ZUK Z2 Plus
ROM版本：AEX 6.2(安卓9.0)
Xposed模块：未开启
APP：系统相机

问题描述：相机直接闪退，且第三方相机也无法使用

其他 Magisk 模块：

补充：

**Comment by hxsstime** [comment]
time: 1548141163190
msg: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
stacktrace: java.lang.RuntimeException: Unable to resume activity {org.lineageos.snap/com.android.camera.CameraLauncher}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3824)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3856)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.android.camera.PhotoModule.initializeFocusManager(PhotoModule.java:2825)
	at com.android.camera.PhotoModule.onResumeBeforeSuper(PhotoModule.java:2599)
	at com.android.camera.CameraActivity.onResume(CameraActivity.java:1862)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
	at android.app.Activity.performResume(Activity.java:7300)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3816)
	... 11 more


-----------------------------------------------------------------------------------------
以上为崩溃日志链接链接的内容，有没有用我也不清楚……
因为并不是直接的崩溃日志……

**Comment by tiann** [comment]
https://github.com/tiann/EXposed/releases/tag/3.3-a 是否修复了这个问题？

**Comment by hxsstime** [comment]
3.3.b未能修复该问题

**Comment by tiann** [comment]
[magisk-taichi-v3.3-c.zip](https://github.com/tiann/EXposed/files/2791208/magisk-taichi-v3.3-c.zip)

帮忙尝试下这个版本，注意备份数据

**Comment by hxsstime** [comment]
您好，之前测试到3.6.b，仍无法启用相机：
https://del.dog/jahimugayu

且经过测试，若是挂载RIRU V11模块，同样会导致系统OR第三方相机无法打开的问题

**Comment by hxsstime** [comment]
> [magisk-taichi-v3.3-c.zip](https://github.com/tiann/EXposed/files/2791208/magisk-taichi-v3.3-c.zip)
> 
> 帮忙尝试下这个版本，注意备份数据

您好，之前测试到3.6.b，仍无法启用相机：
https://del.dog/jahimugayu

且经过测试，若是挂载RIRU V11模块，同样会导致系统OR第三方相机无法打开的问题

**Comment by tiann** [comment]
[magisk-taichi-3.7-a.zip](https://github.com/tiann/EXposed/files/2801218/magisk-taichi-3.7-a.zip)

能否帮忙再测试一下？

**Comment by hxsstime** [comment]
> [magisk-taichi-3.7-a.zip](https://github.com/tiann/EXposed/files/2801218/magisk-taichi-3.7-a.zip)
> 
> 能否帮忙再测试一下？

仍然不行，崩溃日志链接：
https://del.dog/irubunesiw

**Comment by hxsstime** [comment]
> [magisk-taichi-3.7-a.zip](https://github.com/tiann/EXposed/files/2801218/magisk-taichi-3.7-a.zip)
> 
> 能否帮忙再测试一下？

![image](https://user-images.githubusercontent.com/46912897/51893491-f95fe000-23df-11e9-8ea2-17d3eb69637c.png)
RIRU方面查询的结果，不知是否有参考价值

**Comment by tiann** [comment]
据说 AEX 6.3 修复了这个问题。

**Comment by hxsstime** [comment]
> 据说 AEX 6.3 修复了这个问题。

是的已修复该问题，之前使用手机浏览器无法回复，抱歉回复晚了
